# Generated by Django 5.0 on 2024-04-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country'], 'verbose_name_plural': 'Taxes'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='shiping_amount',
            new_name='shipping_amount',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='shiping_amount',
            new_name='shipping_amount',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='shiping_amount',
            new_name='shipping_amount',
        ),
    ]
