# Generated by Django 5.0 on 2024-04-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_notification_user_alter_notification_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='payment',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
