# Generated by Django 5.0 on 2024-04-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_options_user_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
    ]
